# main text of home
title: "Sehyun Yun"
bio: ":>"

# twitter summary info
description: ":>"

# if it's an external image, update below for true
external-image: false
picture: /assets/images/sehyun_cropped.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: false

# Resume
resume: true
resume-external: true
resume-url: https://google.com/?q=my+resume

# Site URL (for GitHub Pages)
url: https://nawhji.github.io
baseurl: "/nawhjipage"

permalink: /:title/

# Comments
disqus:
  shortname: github
  categories: [blog, project]

# Social links
instagram: nawhji
linkedin: SehyunYun
github: nawhji
email: nawhji@gmail.com

authors:
  sehyunyun:
    name: Sehyun Yun
    bio: ":>"
    external-image: false
    picture: /assets/images/sehyun_cropped.jpg
    twitter: sehyunyun
  sehyunfoster:
    name: Sehyun Foster
    bio: ":>"
    external-image: false
    picture: /assets/images/sehyun_cropped.jpg
    twitter: sehyunfoster

width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
